# Update prompt
# export PS1="\u@\h: \[\e[1m\]\W\[\e[0m\] $ "
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\W\[\033[m\]\$ "

# Different colors based on filetypes
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# Set locale
export LC_ALL=en_US.UTF-8

# Increase history
export HISTSIZE=5000

# Brew
export PATH="/usr/local/sbin:$PATH"

# Gnuutils from brew
PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"
MANPATH="/usr/local/opt/grep/libexec/gnuman:$MANPATH"

# JAVA
export JAVA_HOME=$(/usr/libexec/java_home)

# GO Path
export GOPATH="$HOME/.go"
export GOROOT="/usr/local/opt/go/libexec"
export PATH="$PATH:/usr/local/go/bin:$(go env GOPATH)/bin:${GOROOT}/bin"

# Bash completion
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

# K8S Editor
export KUBE_EDITOR=$(which vim)

# Custom alias
alias cp='cp -iv'
alias mv='mv -v'
alias rm='rm -iv'
alias ls='gls --color'
alias ping='ping -c4'
alias tmux='TERM=screen-256color tmux'
alias chmod='gchmod --preserve-root'
alias ussh='ssh -A -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias uscp='scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias axel='axel -a -n 20'

function whatismyip() {
  echo $(curl -sk "https://whatismyip.akamai.com")
}

function ipinfo() {
  echo $(curl -s "https://ipinfo.io/$1")
}

# Startship
# eval "$(starship init bash)"

# PyEnv
export PYENV_ROOT="$HOME/.pyenv"
export PATH=$(pyenv root)/shims:$PATH
export PYENV_VIRTUALENV_DISABLE_PROMPT=1 # simulate no prompt behaviour
# pyenv-virtualenv
eval "$(pyenv init -)"
# if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi

# Custom functions
iam_user_name="vishnu"

# function to reset existing tokens
function aws-reset() {
  unset AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_ACCESS_KEY_ID
}

function wrap_mfa_usage() {
  echo "Missing required parameters"
  echo "${FUNCNAME[0]} profile account-number-without-hyphen mfacode"
}


# wrapper to generate temporary token for a profile
# specified in the ~/.aws/credentials file
function wrap_mfa() {
  if [ -n "$3" ]; then
    aws-reset
    eval $(aws --profile "$1" sts get-session-token --serial-number arn:aws:iam::${2}:mfa/${iam_user_name} --token-code $3 | jq -r '"export AWS_ACCESS_KEY_ID=\(.Credentials.AccessKeyId) && export AWS_SECRET_ACCESS_KEY=\(.Credentials.SecretAccessKey) && export AWS_SESSION_TOKEN=\(.Credentials.SessionToken)"')
  else
    wrap_mfa_usage
  fi
}

# example function using wrapper
function personal-aws() {
  wrap_mfa "default" "REPLACE_WITH_ACCOUNT_ID" "$1"
}

function corp-aws() {
  iam_user_name="vsreekum" wrap_mfa "corp" "REPLACE_WITH_ACCOUNT_ID" "$1"
}

# grab current AWS env vars
function save_aws_env() {
    env | grep AWS > ~/env.tmp
}

# apply current AWS env vars (in a different shell session)
function apply_aws_env() {
    env_file="$HOME/env.tmp"
    if [ -f "$env_file" ]; then
        while read line; do
            export "$line"
        done < "$env_file"
    else echo "$env_file not found"
    fi
}

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

if [ -f ~/.bashrc_local ]; then
    source ~/.bashrc_local
fi

function mkandcd() {
    mkdir -p $1 && cd $1
}

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
