syntax enable
set background=dark
" colorscheme solarized
" colorscheme badwolf
colorscheme gruvbox
let g:gruvbox_contrast_dark='hard'

" vim-ariline
let g:airline_theme='badwolf'

" NERDTreeTabs
" Only on GUI
if has("gui_running")
    " NERDTree Size settings
    let g:nerdtree_tabs_open_on_gui_startup
    let g:NERDTreeWinSize=20

    " Press Ctrl-Tab to switch between open tabs (like browser tabs) to
    " the right side. Ctrl-Shift-Tab goes the other way.
    noremap <C-Tab> :tabnext<CR>
    noremap <C-S-Tab> :tabprev<CR>

    " Switch to specific tab numbers with Command-number
    noremap <D-1> :tabn 1<CR>
    noremap <D-2> :tabn 2<CR>
    noremap <D-3> :tabn 3<CR>
    noremap <D-4> :tabn 4<CR>
    noremap <D-5> :tabn 5<CR>
    noremap <D-6> :tabn 6<CR>
    noremap <D-7> :tabn 7<CR>
    noremap <D-8> :tabn 8<CR>
    noremap <D-9> :tabn 9<CR>
    " Command-0 goes to the last tab
    noremap <D-0> :tablast<CR>
endif

" bundled plugins using pathogen
execute pathogen#infect()
syntax on
filetype plugin indent on

" numbering and swapfile location
set nu
set swapfile
set dir=~/.vim/tmp

" font and size
set guifont=source\ code\ pro:h15

" tab formating
set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set expandtab

" Enable whitespace highlighting
set list

" Syntastic defaults
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
let g:syntastic_python_checkers = ['pyflakes']

" More customization
set ruler
set hlsearch
set incsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set autochdir

" ctrlp.vim
set runtimepath^=~/.vim/bundle/ctrlp.vim
